# Site settings
title: "我的Git主页2"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: qqzhao2010@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You cannot improve your past, but you can improve your future. Once time is wasted, life is wasted.
  <br/>Knowledge makes humble, ignorance makes proud.
url: "http://qqzhao.github.io" # the base hostname & protocol for your site
# baseurl: "/" # the subpath of your site, e.g. /blog/
twitter_username: qqzhao
github_username:  qqzhao

# Build settings
markdown: kramdown
